name: Test & Coverage

on: ['push']

jobs:
  test:
    name: Test & Coverage (node v${{ matrix.node }})
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile
      - run: yarn ci
      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.0
